//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace PPOL.MiscService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MiscAPIServiceSoapBinding", Namespace="http://api.sales.cxrm.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseEntity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseObj))]
    public partial class MiscAPIService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getContactOptionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustomerOptionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback createOrganizationOperationCompleted;
        
        private System.Threading.SendOrPostCallback createContactOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MiscAPIService() {
            this.Url = global::PPOL.Properties.Settings.Default.PPOL_Outlook_Plugin_MiscService_MiscAPIService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getContactOptionsCompletedEventHandler getContactOptionsCompleted;
        
        /// <remarks/>
        public event getCustomerOptionsCompletedEventHandler getCustomerOptionsCompleted;
        
        /// <remarks/>
        public event createOrganizationCompletedEventHandler createOrganizationCompleted;
        
        /// <remarks/>
        public event createContactCompletedEventHandler createContactCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.sales.cxrm.com/", ResponseNamespace="http://api.sales.cxrm.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contactOptions getContactOptions([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2) {
            object[] results = this.Invoke("getContactOptions", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((contactOptions)(results[0]));
        }
        
        /// <remarks/>
        public void getContactOptionsAsync(string arg0, string arg1, string arg2) {
            this.getContactOptionsAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void getContactOptionsAsync(string arg0, string arg1, string arg2, object userState) {
            if ((this.getContactOptionsOperationCompleted == null)) {
                this.getContactOptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetContactOptionsOperationCompleted);
            }
            this.InvokeAsync("getContactOptions", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.getContactOptionsOperationCompleted, userState);
        }
        
        private void OngetContactOptionsOperationCompleted(object arg) {
            if ((this.getContactOptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getContactOptionsCompleted(this, new getContactOptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.sales.cxrm.com/", ResponseNamespace="http://api.sales.cxrm.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public customerOptions getCustomerOptions([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2) {
            object[] results = this.Invoke("getCustomerOptions", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((customerOptions)(results[0]));
        }
        
        /// <remarks/>
        public void getCustomerOptionsAsync(string arg0, string arg1, string arg2) {
            this.getCustomerOptionsAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void getCustomerOptionsAsync(string arg0, string arg1, string arg2, object userState) {
            if ((this.getCustomerOptionsOperationCompleted == null)) {
                this.getCustomerOptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerOptionsOperationCompleted);
            }
            this.InvokeAsync("getCustomerOptions", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.getCustomerOptionsOperationCompleted, userState);
        }
        
        private void OngetCustomerOptionsOperationCompleted(object arg) {
            if ((this.getCustomerOptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerOptionsCompleted(this, new getCustomerOptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.sales.cxrm.com/", ResponseNamespace="http://api.sales.cxrm.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public organization createOrganization([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] organization arg3) {
            object[] results = this.Invoke("createOrganization", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3});
            return ((organization)(results[0]));
        }
        
        /// <remarks/>
        public void createOrganizationAsync(string arg0, string arg1, string arg2, organization arg3) {
            this.createOrganizationAsync(arg0, arg1, arg2, arg3, null);
        }
        
        /// <remarks/>
        public void createOrganizationAsync(string arg0, string arg1, string arg2, organization arg3, object userState) {
            if ((this.createOrganizationOperationCompleted == null)) {
                this.createOrganizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateOrganizationOperationCompleted);
            }
            this.InvokeAsync("createOrganization", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3}, this.createOrganizationOperationCompleted, userState);
        }
        
        private void OncreateOrganizationOperationCompleted(object arg) {
            if ((this.createOrganizationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createOrganizationCompleted(this, new createOrganizationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.sales.cxrm.com/", ResponseNamespace="http://api.sales.cxrm.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contact createContact([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] contact arg3, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool arg4) {
            object[] results = this.Invoke("createContact", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4});
            return ((contact)(results[0]));
        }
        
        /// <remarks/>
        public void createContactAsync(string arg0, string arg1, string arg2, contact arg3, bool arg4) {
            this.createContactAsync(arg0, arg1, arg2, arg3, arg4, null);
        }
        
        /// <remarks/>
        public void createContactAsync(string arg0, string arg1, string arg2, contact arg3, bool arg4, object userState) {
            if ((this.createContactOperationCompleted == null)) {
                this.createContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateContactOperationCompleted);
            }
            this.InvokeAsync("createContact", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4}, this.createContactOperationCompleted, userState);
        }
        
        private void OncreateContactOperationCompleted(object arg) {
            if ((this.createContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createContactCompleted(this, new createContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class contactOptions : baseObj {
        
        private contactAddressType[] addressTypeListField;
        
        private contactCategory[] categoryListField;
        
        private contactPhoneType[] phoneTypeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contactAddressType[] addressTypeList {
            get {
                return this.addressTypeListField;
            }
            set {
                this.addressTypeListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contactCategory[] categoryList {
            get {
                return this.categoryListField;
            }
            set {
                this.categoryListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public contactPhoneType[] phoneTypeList {
            get {
                return this.phoneTypeListField;
            }
            set {
                this.phoneTypeListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class contactAddressType : option {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customerPhoneType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customerCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customerBusinessline))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customerAddressType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(contactPhoneType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(contactCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(contactAddressType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class option : baseObj {
        
        private int idField;
        
        private string keyField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customerOptions))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(option))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customerPhoneType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customerCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customerBusinessline))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customerAddressType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(contactPhoneType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(contactCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(contactAddressType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(contactOptions))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class baseObj {
        
        private string errorMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(contact))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cpPhone))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cpEmail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseCustomFieldData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cpAddress))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(organization))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class baseEntity {
        
        private string activeStatusField;
        
        private int dbCreatedByField;
        
        private System.DateTime dbCreationDateField;
        
        private bool dbCreationDateFieldSpecified;
        
        private System.DateTime dbLastUpdateDateField;
        
        private bool dbLastUpdateDateFieldSpecified;
        
        private int dbLastUpdatedByField;
        
        private string errorMsgField;
        
        private int olCreatedByField;
        
        private System.DateTime olCreationDateField;
        
        private bool olCreationDateFieldSpecified;
        
        private System.DateTime olLastUpdateDateField;
        
        private bool olLastUpdateDateFieldSpecified;
        
        private int olLastUpdatedByField;
        
        private int xmlIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string activeStatus {
            get {
                return this.activeStatusField;
            }
            set {
                this.activeStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dbCreatedBy {
            get {
                return this.dbCreatedByField;
            }
            set {
                this.dbCreatedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dbCreationDate {
            get {
                return this.dbCreationDateField;
            }
            set {
                this.dbCreationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dbCreationDateSpecified {
            get {
                return this.dbCreationDateFieldSpecified;
            }
            set {
                this.dbCreationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dbLastUpdateDate {
            get {
                return this.dbLastUpdateDateField;
            }
            set {
                this.dbLastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dbLastUpdateDateSpecified {
            get {
                return this.dbLastUpdateDateFieldSpecified;
            }
            set {
                this.dbLastUpdateDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dbLastUpdatedBy {
            get {
                return this.dbLastUpdatedByField;
            }
            set {
                this.dbLastUpdatedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int olCreatedBy {
            get {
                return this.olCreatedByField;
            }
            set {
                this.olCreatedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime olCreationDate {
            get {
                return this.olCreationDateField;
            }
            set {
                this.olCreationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool olCreationDateSpecified {
            get {
                return this.olCreationDateFieldSpecified;
            }
            set {
                this.olCreationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime olLastUpdateDate {
            get {
                return this.olLastUpdateDateField;
            }
            set {
                this.olLastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool olLastUpdateDateSpecified {
            get {
                return this.olLastUpdateDateFieldSpecified;
            }
            set {
                this.olLastUpdateDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int olLastUpdatedBy {
            get {
                return this.olLastUpdatedByField;
            }
            set {
                this.olLastUpdatedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int xmlId {
            get {
                return this.xmlIdField;
            }
            set {
                this.xmlIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class contact : baseEntity {
        
        private cpAddress[] addressesField;
        
        private string birthDateField;
        
        private string channelCodeField;
        
        private string channelDetailField;
        
        private string contactClassificationField;
        
        private baseCustomFieldData[] customFieldsField;
        
        private int customerIdField;
        
        private int customerNumberField;
        
        private string decisionMakerField;
        
        private string departmentField;
        
        private string displayNameField;
        
        private cpEmail[] emailsField;
        
        private string firstNameField;
        
        private string jobTitleField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        private int netWorthField;
        
        private baseMessage[] notesField;
        
        private cpPhone[] phonesField;
        
        private string responsibilityField;
        
        private string sexField;
        
        private string titleField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public cpAddress[] addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string channelCode {
            get {
                return this.channelCodeField;
            }
            set {
                this.channelCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string channelDetail {
            get {
                return this.channelDetailField;
            }
            set {
                this.channelDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contactClassification {
            get {
                return this.contactClassificationField;
            }
            set {
                this.contactClassificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customFields", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public baseCustomFieldData[] customFields {
            get {
                return this.customFieldsField;
            }
            set {
                this.customFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int customerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string decisionMaker {
            get {
                return this.decisionMakerField;
            }
            set {
                this.decisionMakerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("emails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public cpEmail[] emails {
            get {
                return this.emailsField;
            }
            set {
                this.emailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int netWorth {
            get {
                return this.netWorthField;
            }
            set {
                this.netWorthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public baseMessage[] notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public cpPhone[] phones {
            get {
                return this.phonesField;
            }
            set {
                this.phonesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string responsibility {
            get {
                return this.responsibilityField;
            }
            set {
                this.responsibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class cpAddress : baseEntity {
        
        private string addrLine1Field;
        
        private string addrLine2Field;
        
        private string addrLine3Field;
        
        private string addrLine4Field;
        
        private int addressIdField;
        
        private string addressTypeField;
        
        private string cityField;
        
        private string countryField;
        
        private string postalCodeField;
        
        private string primaryFlagField;
        
        private string stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addrLine1 {
            get {
                return this.addrLine1Field;
            }
            set {
                this.addrLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addrLine2 {
            get {
                return this.addrLine2Field;
            }
            set {
                this.addrLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addrLine3 {
            get {
                return this.addrLine3Field;
            }
            set {
                this.addrLine3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addrLine4 {
            get {
                return this.addrLine4Field;
            }
            set {
                this.addrLine4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int addressId {
            get {
                return this.addressIdField;
            }
            set {
                this.addressIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string primaryFlag {
            get {
                return this.primaryFlagField;
            }
            set {
                this.primaryFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class baseCustomFieldData : baseEntity {
        
        private int cfDataIdField;
        
        private double cfDataNumValueField;
        
        private string cfDataValueField;
        
        private string fieldDefinitionField;
        
        private int fieldDefinitionIdField;
        
        private int ownerTableIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cfDataId {
            get {
                return this.cfDataIdField;
            }
            set {
                this.cfDataIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double cfDataNumValue {
            get {
                return this.cfDataNumValueField;
            }
            set {
                this.cfDataNumValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cfDataValue {
            get {
                return this.cfDataValueField;
            }
            set {
                this.cfDataValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fieldDefinition {
            get {
                return this.fieldDefinitionField;
            }
            set {
                this.fieldDefinitionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fieldDefinitionId {
            get {
                return this.fieldDefinitionIdField;
            }
            set {
                this.fieldDefinitionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ownerTableId {
            get {
                return this.ownerTableIdField;
            }
            set {
                this.ownerTableIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class cpEmail : baseEntity {
        
        private int contactPointIdField;
        
        private string emailAddrField;
        
        private string primaryFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int contactPointId {
            get {
                return this.contactPointIdField;
            }
            set {
                this.contactPointIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string emailAddr {
            get {
                return this.emailAddrField;
            }
            set {
                this.emailAddrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string primaryFlag {
            get {
                return this.primaryFlagField;
            }
            set {
                this.primaryFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class baseMessage : baseEntity {
        
        private string attachmentFileContentField;
        
        private string attachmentFileNameField;
        
        private int msgIdField;
        
        private string msgTitleField;
        
        private string msgTxtField;
        
        private int parentIdField;
        
        private int threadIdField;
        
        private string writerNameField;
        
        private int writerUserIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attachmentFileContent {
            get {
                return this.attachmentFileContentField;
            }
            set {
                this.attachmentFileContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attachmentFileName {
            get {
                return this.attachmentFileNameField;
            }
            set {
                this.attachmentFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int msgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msgTitle {
            get {
                return this.msgTitleField;
            }
            set {
                this.msgTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msgTxt {
            get {
                return this.msgTxtField;
            }
            set {
                this.msgTxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int parentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int threadId {
            get {
                return this.threadIdField;
            }
            set {
                this.threadIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string writerName {
            get {
                return this.writerNameField;
            }
            set {
                this.writerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int writerUserId {
            get {
                return this.writerUserIdField;
            }
            set {
                this.writerUserIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class cpPhone : baseEntity {
        
        private int contactPointIdField;
        
        private string phoneExtensionField;
        
        private string phoneLineTypeField;
        
        private string phoneNumberField;
        
        private string primaryFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int contactPointId {
            get {
                return this.contactPointIdField;
            }
            set {
                this.contactPointIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phoneExtension {
            get {
                return this.phoneExtensionField;
            }
            set {
                this.phoneExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phoneLineType {
            get {
                return this.phoneLineTypeField;
            }
            set {
                this.phoneLineTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string primaryFlag {
            get {
                return this.primaryFlagField;
            }
            set {
                this.primaryFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class organization : baseEntity {
        
        private cpAddress[] addressesField;
        
        private int annualRevenueField;
        
        private string businessLineField;
        
        private string channelCodeField;
        
        private string channelDetailField;
        
        private baseCustomFieldData[] customFieldsField;
        
        private string customerCategoryField;
        
        private int customerIdField;
        
        private int customerNumberField;
        
        private string displayNameField;
        
        private string dunsNumberField;
        
        private cpEmail[] emailsField;
        
        private string externalPartnerIdField;
        
        private string fiscalYearEndField;
        
        private int netWorthField;
        
        private baseMessage[] notesField;
        
        private int numEmployeeField;
        
        private cpPhone[] phonesField;
        
        private string sicCodeField;
        
        private string stockTickerField;
        
        private string urlField;
        
        private int yearEstablishedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public cpAddress[] addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int annualRevenue {
            get {
                return this.annualRevenueField;
            }
            set {
                this.annualRevenueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string businessLine {
            get {
                return this.businessLineField;
            }
            set {
                this.businessLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string channelCode {
            get {
                return this.channelCodeField;
            }
            set {
                this.channelCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string channelDetail {
            get {
                return this.channelDetailField;
            }
            set {
                this.channelDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customFields", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public baseCustomFieldData[] customFields {
            get {
                return this.customFieldsField;
            }
            set {
                this.customFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string customerCategory {
            get {
                return this.customerCategoryField;
            }
            set {
                this.customerCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int customerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string displayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dunsNumber {
            get {
                return this.dunsNumberField;
            }
            set {
                this.dunsNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("emails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public cpEmail[] emails {
            get {
                return this.emailsField;
            }
            set {
                this.emailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string externalPartnerId {
            get {
                return this.externalPartnerIdField;
            }
            set {
                this.externalPartnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fiscalYearEnd {
            get {
                return this.fiscalYearEndField;
            }
            set {
                this.fiscalYearEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int netWorth {
            get {
                return this.netWorthField;
            }
            set {
                this.netWorthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public baseMessage[] notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numEmployee {
            get {
                return this.numEmployeeField;
            }
            set {
                this.numEmployeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public cpPhone[] phones {
            get {
                return this.phonesField;
            }
            set {
                this.phonesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sicCode {
            get {
                return this.sicCodeField;
            }
            set {
                this.sicCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stockTicker {
            get {
                return this.stockTickerField;
            }
            set {
                this.stockTickerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int yearEstablished {
            get {
                return this.yearEstablishedField;
            }
            set {
                this.yearEstablishedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class customerOptions : baseObj {
        
        private customerAddressType[] addressTypeListField;
        
        private customerBusinessline[] businesslineListField;
        
        private customerCategory[] categoryListField;
        
        private customerPhoneType[] phoneTypeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public customerAddressType[] addressTypeList {
            get {
                return this.addressTypeListField;
            }
            set {
                this.addressTypeListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public customerBusinessline[] businesslineList {
            get {
                return this.businesslineListField;
            }
            set {
                this.businesslineListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public customerCategory[] categoryList {
            get {
                return this.categoryListField;
            }
            set {
                this.categoryListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public customerPhoneType[] phoneTypeList {
            get {
                return this.phoneTypeListField;
            }
            set {
                this.phoneTypeListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class customerAddressType : option {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class customerBusinessline : option {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class customerCategory : option {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class customerPhoneType : option {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class contactPhoneType : option {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.sales.cxrm.com/")]
    public partial class contactCategory : option {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getContactOptionsCompletedEventHandler(object sender, getContactOptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getContactOptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getContactOptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public contactOptions Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((contactOptions)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getCustomerOptionsCompletedEventHandler(object sender, getCustomerOptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerOptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomerOptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public customerOptions Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((customerOptions)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void createOrganizationCompletedEventHandler(object sender, createOrganizationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createOrganizationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createOrganizationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public organization Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((organization)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void createContactCompletedEventHandler(object sender, createContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public contact Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((contact)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591