//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace PPOL.TaskService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TaskAPIServiceSoapBinding", Namespace="http://api.calendar.cxrm.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseObj))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseEntity))]
    public partial class TaskAPIService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getTasksByAssignedUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllTasksOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllTasksByDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTaskDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveTaskRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOpenTasksByAssignedUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllOpenTasksOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTaskOptionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllTasksSyncOperationCompleted;
        
        private System.Threading.SendOrPostCallback transferEmailAsTaskOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TaskAPIService() {
            this.Url = global::PPOL.Properties.Settings.Default.PPOL_Outlook_Plugin_TaskService_TaskAPIService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getTasksByAssignedUserCompletedEventHandler getTasksByAssignedUserCompleted;
        
        /// <remarks/>
        public event getAllTasksCompletedEventHandler getAllTasksCompleted;
        
        /// <remarks/>
        public event getAllTasksByDateCompletedEventHandler getAllTasksByDateCompleted;
        
        /// <remarks/>
        public event getTaskDetailCompletedEventHandler getTaskDetailCompleted;
        
        /// <remarks/>
        public event saveTaskRecordCompletedEventHandler saveTaskRecordCompleted;
        
        /// <remarks/>
        public event getOpenTasksByAssignedUserCompletedEventHandler getOpenTasksByAssignedUserCompleted;
        
        /// <remarks/>
        public event getAllOpenTasksCompletedEventHandler getAllOpenTasksCompleted;
        
        /// <remarks/>
        public event getTaskOptionsCompletedEventHandler getTaskOptionsCompleted;
        
        /// <remarks/>
        public event getAllTasksSyncCompletedEventHandler getAllTasksSyncCompleted;
        
        /// <remarks/>
        public event transferEmailAsTaskCompletedEventHandler transferEmailAsTaskCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.calendar.cxrm.com/", ResponseNamespace="http://api.calendar.cxrm.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public taskList getTasksByAssignedUser([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
            object[] results = this.Invoke("getTasksByAssignedUser", new object[] {
                        arg0,
                        arg1});
            return ((taskList)(results[0]));
        }
        
        /// <remarks/>
        public void getTasksByAssignedUserAsync(string arg0, string arg1) {
            this.getTasksByAssignedUserAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void getTasksByAssignedUserAsync(string arg0, string arg1, object userState) {
            if ((this.getTasksByAssignedUserOperationCompleted == null)) {
                this.getTasksByAssignedUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTasksByAssignedUserOperationCompleted);
            }
            this.InvokeAsync("getTasksByAssignedUser", new object[] {
                        arg0,
                        arg1}, this.getTasksByAssignedUserOperationCompleted, userState);
        }
        
        private void OngetTasksByAssignedUserOperationCompleted(object arg) {
            if ((this.getTasksByAssignedUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTasksByAssignedUserCompleted(this, new getTasksByAssignedUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.calendar.cxrm.com/", ResponseNamespace="http://api.calendar.cxrm.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public taskList getAllTasks([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("getAllTasks", new object[] {
                        arg0});
            return ((taskList)(results[0]));
        }
        
        /// <remarks/>
        public void getAllTasksAsync(string arg0) {
            this.getAllTasksAsync(arg0, null);
        }
        
        /// <remarks/>
        public void getAllTasksAsync(string arg0, object userState) {
            if ((this.getAllTasksOperationCompleted == null)) {
                this.getAllTasksOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllTasksOperationCompleted);
            }
            this.InvokeAsync("getAllTasks", new object[] {
                        arg0}, this.getAllTasksOperationCompleted, userState);
        }
        
        private void OngetAllTasksOperationCompleted(object arg) {
            if ((this.getAllTasksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllTasksCompleted(this, new getAllTasksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.calendar.cxrm.com/", ResponseNamespace="http://api.calendar.cxrm.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public taskList getAllTasksByDate([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2) {
            object[] results = this.Invoke("getAllTasksByDate", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((taskList)(results[0]));
        }
        
        /// <remarks/>
        public void getAllTasksByDateAsync(string arg0, string arg1, string arg2) {
            this.getAllTasksByDateAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void getAllTasksByDateAsync(string arg0, string arg1, string arg2, object userState) {
            if ((this.getAllTasksByDateOperationCompleted == null)) {
                this.getAllTasksByDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllTasksByDateOperationCompleted);
            }
            this.InvokeAsync("getAllTasksByDate", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.getAllTasksByDateOperationCompleted, userState);
        }
        
        private void OngetAllTasksByDateOperationCompleted(object arg) {
            if ((this.getAllTasksByDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllTasksByDateCompleted(this, new getAllTasksByDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.calendar.cxrm.com/", ResponseNamespace="http://api.calendar.cxrm.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public task getTaskDetail([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int arg1) {
            object[] results = this.Invoke("getTaskDetail", new object[] {
                        arg0,
                        arg1});
            return ((task)(results[0]));
        }
        
        /// <remarks/>
        public void getTaskDetailAsync(string arg0, int arg1) {
            this.getTaskDetailAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void getTaskDetailAsync(string arg0, int arg1, object userState) {
            if ((this.getTaskDetailOperationCompleted == null)) {
                this.getTaskDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTaskDetailOperationCompleted);
            }
            this.InvokeAsync("getTaskDetail", new object[] {
                        arg0,
                        arg1}, this.getTaskDetailOperationCompleted, userState);
        }
        
        private void OngetTaskDetailOperationCompleted(object arg) {
            if ((this.getTaskDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTaskDetailCompleted(this, new getTaskDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.calendar.cxrm.com/", ResponseNamespace="http://api.calendar.cxrm.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public task saveTaskRecord([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] task arg1) {
            object[] results = this.Invoke("saveTaskRecord", new object[] {
                        arg0,
                        arg1});
            return ((task)(results[0]));
        }
        
        /// <remarks/>
        public void saveTaskRecordAsync(string arg0, task arg1) {
            this.saveTaskRecordAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void saveTaskRecordAsync(string arg0, task arg1, object userState) {
            if ((this.saveTaskRecordOperationCompleted == null)) {
                this.saveTaskRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveTaskRecordOperationCompleted);
            }
            this.InvokeAsync("saveTaskRecord", new object[] {
                        arg0,
                        arg1}, this.saveTaskRecordOperationCompleted, userState);
        }
        
        private void OnsaveTaskRecordOperationCompleted(object arg) {
            if ((this.saveTaskRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveTaskRecordCompleted(this, new saveTaskRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.calendar.cxrm.com/", ResponseNamespace="http://api.calendar.cxrm.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public taskList getOpenTasksByAssignedUser([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
            object[] results = this.Invoke("getOpenTasksByAssignedUser", new object[] {
                        arg0,
                        arg1});
            return ((taskList)(results[0]));
        }
        
        /// <remarks/>
        public void getOpenTasksByAssignedUserAsync(string arg0, string arg1) {
            this.getOpenTasksByAssignedUserAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void getOpenTasksByAssignedUserAsync(string arg0, string arg1, object userState) {
            if ((this.getOpenTasksByAssignedUserOperationCompleted == null)) {
                this.getOpenTasksByAssignedUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOpenTasksByAssignedUserOperationCompleted);
            }
            this.InvokeAsync("getOpenTasksByAssignedUser", new object[] {
                        arg0,
                        arg1}, this.getOpenTasksByAssignedUserOperationCompleted, userState);
        }
        
        private void OngetOpenTasksByAssignedUserOperationCompleted(object arg) {
            if ((this.getOpenTasksByAssignedUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOpenTasksByAssignedUserCompleted(this, new getOpenTasksByAssignedUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.calendar.cxrm.com/", ResponseNamespace="http://api.calendar.cxrm.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public taskList getAllOpenTasks([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("getAllOpenTasks", new object[] {
                        arg0});
            return ((taskList)(results[0]));
        }
        
        /// <remarks/>
        public void getAllOpenTasksAsync(string arg0) {
            this.getAllOpenTasksAsync(arg0, null);
        }
        
        /// <remarks/>
        public void getAllOpenTasksAsync(string arg0, object userState) {
            if ((this.getAllOpenTasksOperationCompleted == null)) {
                this.getAllOpenTasksOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllOpenTasksOperationCompleted);
            }
            this.InvokeAsync("getAllOpenTasks", new object[] {
                        arg0}, this.getAllOpenTasksOperationCompleted, userState);
        }
        
        private void OngetAllOpenTasksOperationCompleted(object arg) {
            if ((this.getAllOpenTasksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllOpenTasksCompleted(this, new getAllOpenTasksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.calendar.cxrm.com/", ResponseNamespace="http://api.calendar.cxrm.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public taskOptions getTaskOptions([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2) {
            object[] results = this.Invoke("getTaskOptions", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((taskOptions)(results[0]));
        }
        
        /// <remarks/>
        public void getTaskOptionsAsync(string arg0, string arg1, string arg2) {
            this.getTaskOptionsAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void getTaskOptionsAsync(string arg0, string arg1, string arg2, object userState) {
            if ((this.getTaskOptionsOperationCompleted == null)) {
                this.getTaskOptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTaskOptionsOperationCompleted);
            }
            this.InvokeAsync("getTaskOptions", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.getTaskOptionsOperationCompleted, userState);
        }
        
        private void OngetTaskOptionsOperationCompleted(object arg) {
            if ((this.getTaskOptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTaskOptionsCompleted(this, new getTaskOptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.calendar.cxrm.com/", ResponseNamespace="http://api.calendar.cxrm.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public taskList getAllTasksSync([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
            object[] results = this.Invoke("getAllTasksSync", new object[] {
                        arg0,
                        arg1});
            return ((taskList)(results[0]));
        }
        
        /// <remarks/>
        public void getAllTasksSyncAsync(string arg0, string arg1) {
            this.getAllTasksSyncAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void getAllTasksSyncAsync(string arg0, string arg1, object userState) {
            if ((this.getAllTasksSyncOperationCompleted == null)) {
                this.getAllTasksSyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllTasksSyncOperationCompleted);
            }
            this.InvokeAsync("getAllTasksSync", new object[] {
                        arg0,
                        arg1}, this.getAllTasksSyncOperationCompleted, userState);
        }
        
        private void OngetAllTasksSyncOperationCompleted(object arg) {
            if ((this.getAllTasksSyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllTasksSyncCompleted(this, new getAllTasksSyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://api.calendar.cxrm.com/", ResponseNamespace="http://api.calendar.cxrm.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public task transferEmailAsTask([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] task arg3) {
            object[] results = this.Invoke("transferEmailAsTask", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3});
            return ((task)(results[0]));
        }
        
        /// <remarks/>
        public void transferEmailAsTaskAsync(string arg0, string arg1, string arg2, task arg3) {
            this.transferEmailAsTaskAsync(arg0, arg1, arg2, arg3, null);
        }
        
        /// <remarks/>
        public void transferEmailAsTaskAsync(string arg0, string arg1, string arg2, task arg3, object userState) {
            if ((this.transferEmailAsTaskOperationCompleted == null)) {
                this.transferEmailAsTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransferEmailAsTaskOperationCompleted);
            }
            this.InvokeAsync("transferEmailAsTask", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3}, this.transferEmailAsTaskOperationCompleted, userState);
        }
        
        private void OntransferEmailAsTaskOperationCompleted(object arg) {
            if ((this.transferEmailAsTaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transferEmailAsTaskCompleted(this, new transferEmailAsTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.calendar.cxrm.com/")]
    public partial class taskList : baseEntity {
        
        private task[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public task[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.calendar.cxrm.com/")]
    public partial class task : baseEntity {
        
        private string closedFlagField;
        
        private baseCustomFieldData[] customFieldsField;
        
        private string dueDateField;
        
        private string fcABCField;
        
        private string fcDeletedField;
        
        private string fcStatusField;
        
        private baseMessage[] notesField;
        
        private int ownerIdField;
        
        private taskRecurInfoStore recurInfoStoreField;
        
        private calReference[] referencesField;
        
        private string reminderDateField;
        
        private int reminderHourField;
        
        private int reminderMinuteField;
        
        private string taskCategoryField;
        
        private string taskDetailField;
        
        private string taskHistoryField;
        
        private int taskIdField;
        
        private string taskNameField;
        
        private int taskNumberField;
        
        private string taskPriorityField;
        
        private string taskPrivateField;
        
        private string taskStatusField;
        
        private string taskTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string closedFlag {
            get {
                return this.closedFlagField;
            }
            set {
                this.closedFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customFields", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public baseCustomFieldData[] customFields {
            get {
                return this.customFieldsField;
            }
            set {
                this.customFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fcABC {
            get {
                return this.fcABCField;
            }
            set {
                this.fcABCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fcDeleted {
            get {
                return this.fcDeletedField;
            }
            set {
                this.fcDeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fcStatus {
            get {
                return this.fcStatusField;
            }
            set {
                this.fcStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public baseMessage[] notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ownerId {
            get {
                return this.ownerIdField;
            }
            set {
                this.ownerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public taskRecurInfoStore recurInfoStore {
            get {
                return this.recurInfoStoreField;
            }
            set {
                this.recurInfoStoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("references", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public calReference[] references {
            get {
                return this.referencesField;
            }
            set {
                this.referencesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reminderDate {
            get {
                return this.reminderDateField;
            }
            set {
                this.reminderDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int reminderHour {
            get {
                return this.reminderHourField;
            }
            set {
                this.reminderHourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int reminderMinute {
            get {
                return this.reminderMinuteField;
            }
            set {
                this.reminderMinuteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taskCategory {
            get {
                return this.taskCategoryField;
            }
            set {
                this.taskCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taskDetail {
            get {
                return this.taskDetailField;
            }
            set {
                this.taskDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taskHistory {
            get {
                return this.taskHistoryField;
            }
            set {
                this.taskHistoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int taskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taskName {
            get {
                return this.taskNameField;
            }
            set {
                this.taskNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int taskNumber {
            get {
                return this.taskNumberField;
            }
            set {
                this.taskNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taskPriority {
            get {
                return this.taskPriorityField;
            }
            set {
                this.taskPriorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taskPrivate {
            get {
                return this.taskPrivateField;
            }
            set {
                this.taskPrivateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taskStatus {
            get {
                return this.taskStatusField;
            }
            set {
                this.taskStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taskType {
            get {
                return this.taskTypeField;
            }
            set {
                this.taskTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.calendar.cxrm.com/")]
    public partial class baseCustomFieldData : baseEntity {
        
        private int cfDataIdField;
        
        private double cfDataNumValueField;
        
        private string cfDataValueField;
        
        private string fieldDefinitionField;
        
        private int fieldDefinitionIdField;
        
        private int ownerTableIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cfDataId {
            get {
                return this.cfDataIdField;
            }
            set {
                this.cfDataIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double cfDataNumValue {
            get {
                return this.cfDataNumValueField;
            }
            set {
                this.cfDataNumValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cfDataValue {
            get {
                return this.cfDataValueField;
            }
            set {
                this.cfDataValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fieldDefinition {
            get {
                return this.fieldDefinitionField;
            }
            set {
                this.fieldDefinitionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fieldDefinitionId {
            get {
                return this.fieldDefinitionIdField;
            }
            set {
                this.fieldDefinitionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ownerTableId {
            get {
                return this.ownerTableIdField;
            }
            set {
                this.ownerTableIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(taskList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(calReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(task))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseCustomFieldData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.calendar.cxrm.com/")]
    public partial class baseEntity {
        
        private string activeStatusField;
        
        private int dbCreatedByField;
        
        private System.DateTime dbCreationDateField;
        
        private bool dbCreationDateFieldSpecified;
        
        private System.DateTime dbLastUpdateDateField;
        
        private bool dbLastUpdateDateFieldSpecified;
        
        private int dbLastUpdatedByField;
        
        private string errorMsgField;
        
        private int olCreatedByField;
        
        private System.DateTime olCreationDateField;
        
        private bool olCreationDateFieldSpecified;
        
        private System.DateTime olLastUpdateDateField;
        
        private bool olLastUpdateDateFieldSpecified;
        
        private int olLastUpdatedByField;
        
        private int xmlIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string activeStatus {
            get {
                return this.activeStatusField;
            }
            set {
                this.activeStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dbCreatedBy {
            get {
                return this.dbCreatedByField;
            }
            set {
                this.dbCreatedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dbCreationDate {
            get {
                return this.dbCreationDateField;
            }
            set {
                this.dbCreationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dbCreationDateSpecified {
            get {
                return this.dbCreationDateFieldSpecified;
            }
            set {
                this.dbCreationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dbLastUpdateDate {
            get {
                return this.dbLastUpdateDateField;
            }
            set {
                this.dbLastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dbLastUpdateDateSpecified {
            get {
                return this.dbLastUpdateDateFieldSpecified;
            }
            set {
                this.dbLastUpdateDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dbLastUpdatedBy {
            get {
                return this.dbLastUpdatedByField;
            }
            set {
                this.dbLastUpdatedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int olCreatedBy {
            get {
                return this.olCreatedByField;
            }
            set {
                this.olCreatedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime olCreationDate {
            get {
                return this.olCreationDateField;
            }
            set {
                this.olCreationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool olCreationDateSpecified {
            get {
                return this.olCreationDateFieldSpecified;
            }
            set {
                this.olCreationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime olLastUpdateDate {
            get {
                return this.olLastUpdateDateField;
            }
            set {
                this.olLastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool olLastUpdateDateSpecified {
            get {
                return this.olLastUpdateDateFieldSpecified;
            }
            set {
                this.olLastUpdateDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int olLastUpdatedBy {
            get {
                return this.olLastUpdatedByField;
            }
            set {
                this.olLastUpdatedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int xmlId {
            get {
                return this.xmlIdField;
            }
            set {
                this.xmlIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(taskOptions))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(option))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(taskPriority))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(taskStatus))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.calendar.cxrm.com/")]
    public partial class baseObj {
        
        private string errorMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.calendar.cxrm.com/")]
    public partial class taskOptions : baseObj {
        
        private taskPriority[] taskPriorityListField;
        
        private taskStatus[] taskStatusListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public taskPriority[] taskPriorityList {
            get {
                return this.taskPriorityListField;
            }
            set {
                this.taskPriorityListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public taskStatus[] taskStatusList {
            get {
                return this.taskStatusListField;
            }
            set {
                this.taskStatusListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.calendar.cxrm.com/")]
    public partial class taskPriority : option {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(taskPriority))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(taskStatus))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.calendar.cxrm.com/")]
    public partial class option : baseObj {
        
        private int idField;
        
        private string keyField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.calendar.cxrm.com/")]
    public partial class taskStatus : option {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.calendar.cxrm.com/")]
    public partial class taskRecurInfoStore {
        
        private int daySetupField;
        
        private string endDateField;
        
        private string monthSetupField;
        
        private int numTimesField;
        
        private string recurTypeField;
        
        private string startDateField;
        
        private string weekSetupField;
        
        private string yearSetupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int daySetup {
            get {
                return this.daySetupField;
            }
            set {
                this.daySetupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string monthSetup {
            get {
                return this.monthSetupField;
            }
            set {
                this.monthSetupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numTimes {
            get {
                return this.numTimesField;
            }
            set {
                this.numTimesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string recurType {
            get {
                return this.recurTypeField;
            }
            set {
                this.recurTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string weekSetup {
            get {
                return this.weekSetupField;
            }
            set {
                this.weekSetupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string yearSetup {
            get {
                return this.yearSetupField;
            }
            set {
                this.yearSetupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.calendar.cxrm.com/")]
    public partial class calReference : baseEntity {
        
        private int entityIdField;
        
        private string entityNameField;
        
        private string entityTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int entityId {
            get {
                return this.entityIdField;
            }
            set {
                this.entityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string entityName {
            get {
                return this.entityNameField;
            }
            set {
                this.entityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string entityType {
            get {
                return this.entityTypeField;
            }
            set {
                this.entityTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.calendar.cxrm.com/")]
    public partial class baseMessage : baseEntity {
        
        private string attachmentFileContentField;
        
        private string attachmentFileNameField;
        
        private int msgIdField;
        
        private string msgTitleField;
        
        private string msgTxtField;
        
        private int parentIdField;
        
        private int threadIdField;
        
        private string writerNameField;
        
        private int writerUserIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attachmentFileContent {
            get {
                return this.attachmentFileContentField;
            }
            set {
                this.attachmentFileContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string attachmentFileName {
            get {
                return this.attachmentFileNameField;
            }
            set {
                this.attachmentFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int msgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msgTitle {
            get {
                return this.msgTitleField;
            }
            set {
                this.msgTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msgTxt {
            get {
                return this.msgTxtField;
            }
            set {
                this.msgTxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int parentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int threadId {
            get {
                return this.threadIdField;
            }
            set {
                this.threadIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string writerName {
            get {
                return this.writerNameField;
            }
            set {
                this.writerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int writerUserId {
            get {
                return this.writerUserIdField;
            }
            set {
                this.writerUserIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getTasksByAssignedUserCompletedEventHandler(object sender, getTasksByAssignedUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTasksByAssignedUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTasksByAssignedUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taskList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taskList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getAllTasksCompletedEventHandler(object sender, getAllTasksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllTasksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllTasksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taskList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taskList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getAllTasksByDateCompletedEventHandler(object sender, getAllTasksByDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllTasksByDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllTasksByDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taskList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taskList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getTaskDetailCompletedEventHandler(object sender, getTaskDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTaskDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTaskDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public task Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((task)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void saveTaskRecordCompletedEventHandler(object sender, saveTaskRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveTaskRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveTaskRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public task Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((task)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getOpenTasksByAssignedUserCompletedEventHandler(object sender, getOpenTasksByAssignedUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOpenTasksByAssignedUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOpenTasksByAssignedUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taskList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taskList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getAllOpenTasksCompletedEventHandler(object sender, getAllOpenTasksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllOpenTasksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllOpenTasksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taskList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taskList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getTaskOptionsCompletedEventHandler(object sender, getTaskOptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTaskOptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTaskOptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taskOptions Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taskOptions)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getAllTasksSyncCompletedEventHandler(object sender, getAllTasksSyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllTasksSyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllTasksSyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taskList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taskList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void transferEmailAsTaskCompletedEventHandler(object sender, transferEmailAsTaskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transferEmailAsTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transferEmailAsTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public task Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((task)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591